In [ ]:
import numpy as np

A = np.array ([[3,  2], [7,  -2]])

x, v = np.linalg.eig (A)

print(A)
print("Valores propios: ", x)
print("Vectores propios: ", v)

[[ 3  2]
 [ 7 -2]]
Valores propios:  [ 5. -4.]
Vectores propios:  [[ 0.70710678 -0.27472113]
 [ 0.70710678  0.96152395]]


In [ ]:
np.dot(v[0], v[1])

0.23584905660377342

En este caso, tenemos dos ***valores propios*** y dos ***vectores propios***.

Siempre la relación de proporcionalidad entre ***valores propios*** y ***vectores propios*** será de [1 : 1].

Por esta razón, si hay un ***valor propio***, necesariamente tiene que haber un solo ***vector propio*** y viceversa; lo mismo que si hay dos, tres o n.

La fórmula de esta regla es:

$Ax = \lambda x$

Entonces, el ***valor propio*** del primer vector es 5 y el ***valor propio*** del segundo vector es -4.


In [ ]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
w, v = np.linalg.eig(np.diag((1, 2, 3)))
print(w)
print(v)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = [[3,  2], [7,  -2]]
v1, v2 = np.linalg.eigvals(a)
print(v1)
print(v2)

5.0
-4.0


In [ ]:
M = [[1,0,0], [0,0,-1],[0,1,0]]
w, v = np.linalg.eig(M)
print(w)
print(v)

[0.+1.j 0.-1.j 1.+0.j]
[[0.        +0.j         0.        -0.j         1.        +0.j        ]
 [0.70710678+0.j         0.70710678-0.j         0.        +0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j 0.        +0.j        ]]
